apiVersion: v1
kind: Secret
metadata:
    name: go-kirana-products-secret
    namespace: products
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:z5H8xg==,iv:Uc4ohFue/2BhBmKNonRlilq8l3p15D9QRR/Tr+OUvf4=,tag:Ot7HpIxOvvgk7gUtAIHzRw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:l1CDeA==,iv:mQKIXlhLs+k24YD/H/j07k/KZxBi+lMcADPh+AwH5G0=,tag:U42pw7Urt2PHqwGBLr8BdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qlxrg8ttjk8q9u85e55ktdqk5a6s3m4503w53tuu5xnln92cae5s00cdsh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVGdmWXBMcFEraUJuTWND
            QkJDWld0dC9BanYxLzhKdHdZd2VNOGZmOUZjCkFZMzk5eGZINzJ4UGVZZlYrUklm
            cmNJRThTNG5FRFNPK0ZldUZsV3p5RkkKLS0tIEZNdXdzWjd4SW5VWmMvWVcybEV2
            YUhLT1d3THNKejdQaHhrbUpZYWRCSlUKEHsmDCRO6t7VxrVQURlJXpAYPSO8lX/o
            g7ab3HloZ6UyI0R/tgVl9F91E/fB9UQxlI8thrN7Wx+kDtNv2Gowhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T08:48:32Z"
    mac: ENC[AES256_GCM,data:o55WNLlsQ+ty5qUCUc+BvHPHSb6qAFm+zW5F5NZFCUt725Vf0LwFFSB8kqOKsnVMwFbqPPRGYC5e1l5wk+J7nk7xIBK+0LysVxzK4NwgN9tWKN35c8wSbfmeGBdUVXb6dB81vKwXFXp0r1qHoXbh7bsvcChYMenwaJt4gQGUjUQ=,iv:e4DxyeUM7/W4vlR3eHviT5dJ3OvEQLsFERA9Su26UsY=,tag:IojK7xgAqMidU63U/h1vNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
